# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        /:year/:title/

# Setup
title:            mitchchn.me
tagline:          Computers, coffee, code, and giant spiders.
description:      Base theme for Jekyll themes by @mdo.
url:              http://mitchchn.me
paginate:         3

# Me
author:
  name:           Mitchell Cohen
  url:            https://twitter.com/mitchchn


# Posts
excerpt_separator: "<!--more-->"


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mitchchn

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# RSS

name: mitchchn.me
description: "Coffee, Code, Language and Giant Spiders - By Mitchell Cohen"
url: http://mitchchn.me