# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty  

# Setup
title:            mitchchn.me
tagline:          Computers, coffee, code, and giant spiders.
description:      Base theme for Jekyll themes by @mdo.
url:              http://mitchchn.me

author:
  name:           Mitchell Cohen
  url:            https://twitter.com/mitchchn

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mitchchn
